program: sentiment_train.py
method: random  # or "grid" / "bayes"
metric:
  name: val_accuracy
  goal: maximize
parameters:
  max_epochs:
    value: 20
  batch_size:
    values: [32, 64]
  learning_rate:
    distribution: uniform
    min: 1e-4
    max: 5e-4
  block_size:
    value: 256
  n_layer:
    values: [6, 8]
  n_head:
    values: [6, 8]
  n_embd:
    values: [384, 512]
  dropout:
    values: [0.1, 0.2]
  bias:
    value: true
