_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 16
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: false
block_size:
    value: 256
compile:
    value: false
dataset:
    value: openwebtext
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0.2
dtype:
    value: bfloat16
eval_interval:
    value: 10
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 40
init_from:
    value: scratch
learning_rate:
    value: 0.0006
log_interval:
    value: 1
lr_decay_iters:
    value: 1000
max_iters:
    value: 1000
min_lr:
    value: 6e-05
n_embd:
    value: 256
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out-sentiment-small
wandb_log:
    value: true
wandb_project:
    value: (1000)sentiment-classification
wandb_run_name:
    value: sentiment-small-gpt
warmup_iters:
    value: 2000
weight_decay:
    value: 0.1
