_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.1
            "6": 4.51.0
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 12
beta1:
    value: 0.9
beta2:
    value: 0.95
bias:
    value: true
block_size:
    value: 1024
compile:
    value: false
dataset:
    value: customer_service
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0.1
dtype:
    value: bfloat16
eval_interval:
    value: 2000
eval_iters:
    value: 200
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 40
init_from:
    value: gpt2
learning_rate:
    value: 0.0001
log_interval:
    value: 1
lr_decay_iters:
    value: 500
max_iters:
    value: 500
min_lr:
    value: 6e-05
n_embd:
    value: 768
n_head:
    value: 12
n_layer:
    value: 12
out_dir:
    value: out-sentiment-finetune
wandb_log:
    value: true
wandb_project:
    value: DI725-A1
wandb_run_name:
    value: finetune_sentiment_run
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
